version: '3.8'

services:
  db:
    image: postgres:9.6.23
    restart: unless-stopped
    container_name: workbulk_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

volumes:
  db-data:
      driver: local
  db-files:


networks:
  backend:
    driver: bridge

