version: '3.8'

services:
  db:
    image: annalieks/workbulk_db
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    networks:
      - workbulk

  backend:
    image: annalieks/workbulk_backend
    restart: unless-stopped
    ports:
      - "7070:7070"
    depends_on:
      - db
    networks:
      - workbulk
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1.5G

  frontend:
    image: annalieks/workbulk_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - workbulk
    domainname: workbulk
    environment:
      BACKEND_URL: http://backend:7070
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1.5G

  # caddy:
  #   image: caddy:2.4.5-alpine
  #   restart: unless-stopped
  #   command: caddy reverse-proxy --from http://workbulk.eastus.azurecontainer.io:80 --to http://frontend:3000
  #   ports:
  #     - "80:80"
  #     # - "443:443"
  #   depends_on:
  #     - frontend
  #   domainname: workbulk
  #   networks:
  #     - workbulk
  #   deploy:
  #     resources:
  #       reservations:
  #         cpus: '0.5'
  #         memory: 1.5G

networks:
  workbulk:
    driver: bridge




